/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111383-g20b8688092-20230709"
#endif /* AVUTIL_FFVERSION_H */
